global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
